spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        #        use_sql_comments: true
        hbm2ddl:
          auto: update #create
        default_batch_fetch_size: 1000

  kakao:
    client-id: ${KAKAO_API_KEY}
    redirect-uri: ${KAKAO_REDIRECT_URI}

  jwt:
    secret: ${SECRET_JWT}
    access-token-expiration: 1800000 # 30분 (단위: milliseconds)
    refresh-token-expiration: 1209600000 # 14일 (2주)